services:
   smrt:
      image: smrt/smrt:latest
      build:
         context: .
         dockerfile: Dockerfile
      container_name: smrt
      ports:
         - "5000:5000"
      volumes:
      - ./config.yml:/app/config.yml
      - ./storage/:/storage/
      restart: unless-stopped
