version: "3.6"
services:
   smrt:
      environment: 
      - OPENAI_APIKEY=openaiapi
      - WPPCONNECT_APIKEY=sessionforsmrt
      - WPPCONNECT_SERVER=http://yourserver:21465
      - MIN_WORDS_FOR_SUMMARY=10
