version: '3'
services:
  ollama:
    build: .
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./data:/root/.ollama
    networks:
      - smrt-network
networks:
    smrt-network:
      external: true
