version: '3'
services:
  ollama:
    build: .
    image: ollama/ollama
    container_name: ollama
    ports:
      - "127.0.0.1:11434:11434"
    volumes:
      - ./data:/root/.ollama
    restart: unless-stopped
